version: "3.8"
services:
    postgres:
        image: "postgres"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "donatas"
            POSTGRES_DB: "temp"
        ports:
            - "5432:5432"
        volumes:
            - "./temp/postgres_data:/var/lib/postgresql/data"
